BookShop/Controllers/ApplicationTypeController.cs
using BookShop.DataAccess.Repository.IRepository;
using BookShop.Models.Models;
using BookShop.Utility.Constans;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Syncfusion.EJ2.Layouts;

namespace BookShop.Controllers;

[Authorize(Roles = WebConstans.AdminRole)]
public class ApplicationTypeController : Controller
{
    private readonly IApplicationTypeRepository appRepo;

    public ApplicationTypeController(IApplicationTypeRepository appRepo)
    {
        this.appRepo = appRepo;
    }

    public IActionResult Index()
    {
        IEnumerable<ApplicationType> itemList = appRepo.GetAll();
        return View(itemList);
    }

    //GET - CREATE
    public IActionResult Create()
    {
        return View();
    }

    //POST - CREATE
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(ApplicationType item)
    {
        if (ModelState.IsValid)
        {
            CreateApplicationType(item);
        }

        return View(item);
    }
    private IActionResult CreateApplicationType(ApplicationType item)
    {
        appRepo.Add(item);
        appRepo.Save();
        TempData[WebConstans.Success] = "Action completed successfully";

        return RedirectToAction("Index");
    }


    //GET - EDIT
    public IActionResult Edit(int? id)
    {
        if (!IsIdValid(id))
        {
            return NotFound();
        }

        var item = appRepo.Find(id.GetValueOrDefault());
        if (item == null)
        {
            return NotFound();
        }

        return View(item);
    }

    //POST - EDIT
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(ApplicationType item)
    {
        if (ModelState.IsValid)
        {
            UpdateApplicationType(item);
        }
        return View(item);

    }
    private IActionResult UpdateApplicationType(ApplicationType item)
    {
        appRepo.Update(item);
        appRepo.Save();
        TempData[WebConstans.Success] = "Action completed successfully";

        return RedirectToAction("Index");
    }


    //GET - DELETE
    public IActionResult Delete(int? id)
    {
        if (!IsIdValid(id))
        {
            return NotFound();
        }

        var item = appRepo.Find(id.GetValueOrDefault());
        if (item == null)
        {
            return NotFound();
        }

        return View(item);
    }

    //POST - DELETE
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult DeletePost(int? id)
    {
        var item = appRepo.Find(id.GetValueOrDefault());
        if (item == null)
        {
            return NotFound();
        }

        appRepo.Remove(item);
        appRepo.Save();
        TempData[WebConstans.Success] = "Action completed successfully";

        return RedirectToAction("Index");
    }

    private bool IsIdValid(int? id)
    {
        return id != null && id != 0;
    }
}

BookShop/Controllers/CartController.cs
using BookShop.DataAccess.Repository.IRepository;
using BookShop.Models.Models;
using BookShop.Models.ViewModels;
using BookShop.Services.Interfaces;
using BookShop.Utility.BrainTree;
using BookShop.Utility.Constans;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BookShop.Controllers;

[Authorize]
public class CartController : Controller
{
    private readonly IOrderHeaderRepository orderHeaderRepo;
    private readonly IBrainTreeGate brainGate;
    private readonly ICartService cartService;

    [BindProperty]
    public ProductUserViewModel ProductUserViewModel { get; set; }

    public CartController(IOrderHeaderRepository orderHeaderRepo, IBrainTreeGate brainGate, ICartService cartService)
    {
        this.orderHeaderRepo = orderHeaderRepo;
        this.brainGate = brainGate;
        this.cartService = cartService;
    }

    [HttpGet]
    public IActionResult Index()
    {
        var shoppingCartList = cartService.GetCartFromSession(HttpContext);
        var productList = cartService.GenerateProductList(shoppingCartList);

        return View(productList);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    [ActionName("Index")]
    public IActionResult IndexPost(IEnumerable<Product> products)
    {
        cartService.UpdateCountInCart(products, HttpContext);

        return RedirectToAction(nameof(Summary));
    }

    [HttpGet]
    public IActionResult Summary()
    {
        ApplicationUser applicationUser;
        
        if (User.IsInRole(WebConstans.AdminRole))
        {
            applicationUser = cartService.GetUserForAdmin(HttpContext);
            GenerateBraintreeClientToken(brainGate);
        }
        else
        {
            applicationUser = cartService.GetUserForRegularUser(User);
        }

        var shoppingCart = cartService.GetCartFromSession(HttpContext);
        cartService.GetListProductFromDBBasedOnCart(shoppingCart);

        ProductUserViewModel = cartService.GetListFromCartUserViewModel(applicationUser, shoppingCart, ProductUserViewModel);

        return View(ProductUserViewModel);
    }

    private void GenerateBraintreeClientToken(IBrainTreeGate brainGate)
    {
        var clientToken = brainGate.GetClientToken(brainGate);

        ViewBag.ClientToken = clientToken;
    }

    [HttpPost]
    [ActionName("Summary")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> SummaryPost(IFormCollection collection, ProductUserViewModel productUserViewModel)
    {
        var claim = cartService.GetClaimIdentityUser(User);

        if (User.IsInRole(WebConstans.AdminRole))
        {
            return await ProcessAdminOrder(collection, productUserViewModel, claim);
        }
        else
        {
            return await ProcessUserInquiry(productUserViewModel, claim);
        }
    }

    private async Task<IActionResult> ProcessAdminOrder(IFormCollection collection, ProductUserViewModel productUserViewModel, Claim claim)
    {
        var resultOrderHeader = cartService.ProcessAdminOrder(collection, productUserViewModel, claim);

        return RedirectToAction(nameof(InquiryConfirmation), new { id = resultOrderHeader.Id });
    }
    private async Task<IActionResult> ProcessUserInquiry(ProductUserViewModel productUserViewModel, Claim claim)
    {
        cartService.ProcessUserInquiry(productUserViewModel, claim);

        TempData[WebConstans.Success] = "Inquiry submitted successfully";

        return RedirectToAction(nameof(InquiryConfirmation));
    }

    public IActionResult InquiryConfirmation(int id = 0)
    {
        var orderHeader = orderHeaderRepo.FirstOrDefault(i => i.Id == id);
        
        HttpContext.Session.Clear();

        return View();
    }

    public IActionResult Remove(int id)
    {
        cartService.Remove(id, HttpContext);

        return RedirectToAction(nameof(Index));
    }

    public IActionResult Clear()
    {
        HttpContext.Session.Clear();

        return RedirectToAction("Index", "Home");
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult UpdateCart(IEnumerable<Product> products)
    {
        cartService.UpdateCountInCart(products, HttpContext);

        return RedirectToAction(nameof(Index));
    }

}

BookShop/Controllers/CategoryController.cs
using BookShop.DataAccess.Repository.IRepository;
using BookShop.Models.Models;
using BookShop.Utility.Constans;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BookShop.Controllers;

[Authorize(Roles = WebConstans.AdminRole)]
public class CategoryController : Controller
{
    private readonly ICategoryRepository catRepo;

    public CategoryController(ICategoryRepository catRepo)
    {
        this.catRepo = catRepo;
    }

    public IActionResult Index()
    {
        IEnumerable<Category> categoriesList = catRepo.GetAll();

        return View(categoriesList);
    }

    //Get - create
    public IActionResult Create()
    {
        return View();
    }


    //Post - create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(Category category)
    {

        if(ModelState.IsValid)
        {
            CreateProduct(category);
        }

        TempData[WebConstans.Error] = "Error while creating category";

        return View(category);
    }

    private IActionResult CreateProduct(Category category)
    {
        catRepo.Add(category);
        catRepo.Save();
        TempData[WebConstans.Success] = "Category created sucessfully";

        return RedirectToAction("Index");
    }

    //Get edit
    public IActionResult Edit(int? id)
    {
        if (!IsIdValid(id))
        {
            return NotFound();
        }

        var item = catRepo.Find(id.GetValueOrDefault());
        if (item == null)
        {
            return NotFound();
        }

        return View(item);
    }

    //Post - edit
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(Category category)
    {
        if (ModelState.IsValid)
        {
            catRepo.Update(category);
            catRepo.Save();

            return RedirectToAction("Index");
        }

        return View(category);
    }


    //Get delete
    public IActionResult Delete(int? id)
    {
        if (!IsIdValid(id))
        {
            return NotFound();
        }

        var item = catRepo.Find(id.GetValueOrDefault());
        if (item == null)
        {
            return NotFound();
        }

        return View(item);
    }

    //Post - delete
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult DeletePost(int? Id)
    {
        var item = catRepo.Find(Id.GetValueOrDefault());
        if (item == null)
        {
            return NotFound();
        }

        catRepo.Remove(item);
        catRepo.Save();

        return RedirectToAction("Index");
    }

    private bool IsIdValid(int? id)
    {
        return id != null && id != 0;
    }
}

BookShop/Controllers/InquiryController.cs
using BookShop.DataAccess.Repository.IRepository;
using BookShop.Extensions;
using BookShop.Models.Models;
using BookShop.Models.ViewModels;
using BookShop.Utility.Constans;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BookShop.Controllers;

[Authorize(Roles = WebConstans.AdminRole)]
public class InquiryController : Controller
{
    private readonly IInquiryHeaderRepository inquiryHeaderRepo;
    private readonly IInquiryDetailRepository inquiryDetailRepo;

    [BindProperty]
    public InquiryViewModel InquiryViewModel { get; set; }

    public InquiryController(IInquiryHeaderRepository inquiryHeaderRepo, IInquiryDetailRepository inquiryDetailRepo)
    {
        this.inquiryHeaderRepo = inquiryHeaderRepo;
        this.inquiryDetailRepo = inquiryDetailRepo;
    }

    public IActionResult Index()
    {
        return View();
    }

    [HttpGet]
    public IActionResult Details(int id)
    {
        InquiryViewModel = GetInquiryViewModel(id);
       
        return View(InquiryViewModel);
    }

    private InquiryViewModel GetInquiryViewModel(int id)
    {
        return new InquiryViewModel
        {
            InquiryHeader = inquiryHeaderRepo.FirstOrDefault(i => i.Id == id),
            InquiryDetail = inquiryDetailRepo.GetAll(i => i.InquiryHeaderId == id, includeProperties: "Product")
        };
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Details()
    {
        InquiryViewModel.InquiryDetail = inquiryDetailRepo.GetAll(i => i.InquiryHeaderId == InquiryViewModel.InquiryHeader.Id);
        
        var shoppingCartList = CreateShoppingCartList(InquiryViewModel);

        SetSession(shoppingCartList);

        return RedirectToAction("Index", "Cart");
    }

    private List<ShoppingCart> CreateShoppingCartList(InquiryViewModel inquiryViewModel)
    {
        var shoppingCartList = new List<ShoppingCart>();

        foreach (var detail in inquiryViewModel.InquiryDetail)
        {
            var shoppingCart = new ShoppingCart
            {
                ProductId = detail.ProductId
            };

            shoppingCartList.Add(shoppingCart);
        }

        return shoppingCartList;
    }

    private void SetSession(List<ShoppingCart> shoppingCartList)
    {
        HttpContext.Session.Clear();
        HttpContext.Session.Set(WebConstans.SessionCart, shoppingCartList);
        HttpContext.Session.Set(WebConstans.SessionInquiryId, InquiryViewModel.InquiryHeader.Id);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Delete()
    {
        DeleteInquiry();
        TempData[WebConstans.Success] = "Action completed successfully";

        return RedirectToAction(nameof(Index));
    }

    private void DeleteInquiry()
    {
        var inquiryHeader = inquiryHeaderRepo.FirstOrDefault(i => i.Id == InquiryViewModel.InquiryHeader.Id);
        IEnumerable<InquiryDetail> inquiryDetails = inquiryDetailRepo.GetAll(i => i.InquiryHeaderId == InquiryViewModel.InquiryHeader.Id);

        inquiryDetailRepo.RemoveRange(inquiryDetails);
        inquiryHeaderRepo.Remove(inquiryHeader);
        inquiryHeaderRepo.Save();

    }

    // APICALLS

    [HttpGet]
    public IActionResult GetInquiryList()
    {
        return Json(new { data = inquiryHeaderRepo.GetAll() });
    }

}

BookShop/Views/Shared/_IndividualProductCard.cshtml
@using BookShop.Utility.Constans
@model BookShop.Models.Models.Product

<div class="col-lg-4 col-md-6 pb-4 filter @Model.Category.Name.Replace(' ', '_')">
    <!-- Card-->
    <div class="card bg-white rounded shadow-sm" style="border:1px solid #222">
        <div class="card-body px-3 pt-3 pb-1 row">
            <div class="col-7"><label class="float-left">@Model.Name</label></div>
            <div class="col-5"><label class="float-right"><span class="text-info h5">@string.Format("{0:c0}", Model.Price)</span> / sqft</label> </div>
        </div>
        <img class="card-img-top img-fluid d-block mx-auto mb-3" src="@WebConstans.ImagePath@Model.Image" alt="Card image cap">
        <div class="card-body p-1 px-3 row">
            <div class="col-6">
                <span class="badge p-2 border w-100 text-dark" style="background-color:lavenderblush">@Model.Category.Name</span>
            </div>
            <div class="col-6 border-0">
                <span class="badge p-2 border w-100 text-dark" style="background-color:aliceblue">@Model.ApplicationType.Name</span>
            </div>
            <div class="col-12 pt-2" style="font-size:13px; text-align:justify">
                <p> @Model.ShortDesc</p>
            </div>
            <div class="col-12 p-1">
                <a asp-action="Details" asp-route-id="@Model.Id" class="btn btn-dark form-control btn-sm p-2" style="height:40px">View Details</a>
            </div>
        </div>
    </div>
</div>

BookShop/Views/Shared/_Layout.cshtml
@using BookShop.Extensions
@using BookShop.Models.Models
@using BookShop.Utility.Utility
@using BookShop.Utility.Constans
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookShop</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous"/>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.5/css/dataTables.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.5/css/dataTables.bootstrap5.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.5/css/dataTables.dataTables.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" />
    <link href="~/FontAwesome/css/all.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/material.css" />
    <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/25.1.35/fluent.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/tile.png" width="40%" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial"/>

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole(WebConstans.AdminRole))
                        {
                            <li class="nav-item dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false">
                                    Content management
                                </button>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="ApplicationType" asp-action="Index">Application Type</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create Admin User</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Order/Inquiry Management
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="" asp-controller="Inquiry" asp-action="Index">Inquiry</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Order" asp-action="Index">Order</a>
                                </div>
                            </li>
                        }
                        <li>
                            @if (HttpContextAccessor.HttpContext.Session.Get<List<ShoppingCart>>(WebConstans.SessionCart) != null)
                            {
                                <a asp-action="Index" asp-controller="Cart" class="nav-link">
                                    @{
                                        var count = HttpContextAccessor.HttpContext.Session.Get<List<ShoppingCart>>(WebConstans.SessionCart).Count;
                                    }
                                    <i class="fas fa-shopping-cart"></i> &nbsp; (@count)
                                </a>
                            }
                            else
                            {
                                 <a href="#" class="nav-link">
                                    <i class="fas fa-shopping-cart"></i> &nbsp; (0)
                                 </a>
                            }
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container mb-4 pb-4">
        <main role="main" class="pb-3">
            <partial name="_Notifications" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-dark">
        <div class="container text-white-50">
            &copy; 2024 - BookShop
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/2.0.5/js/dataTables.bootstrap5.min.js"></script>
    <script src="https://cdn.datatables.net/2.0.5/js/dataTables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.syncfusion.com/ej2/dist/ej2.min.js"></script>
    <script src="https://cdn.syncfusion.com/ej2/25.1.35/dist/ej2.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <ejs-scripts></ejs-scripts>
</body>
</html>

BookShop/Views/Shared/_Notifications.cshtml
@using BookShop.Utility.Constans

@if (TempData[WebConstans.Success] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData[WebConstans.Success]');
    </script>
}
@if (TempData[WebConstans.Error] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData[WebConstans.Error]');
    </script>
}